name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check required files
        run: |
         test -f siteToys/html/index.html
         test -f siteToys/css/style.css
         test -f siteToys/img/logo.png
         test -f siteToys/ing/does-not-exist.png
         echo "Required files exist"
